### ISSUE TITLE
tablet-report-parser.pl should handle empty node information from tablet report

### ISSUE THREAD

**Issue by eugeneckim** [yugabyte/yb-tools#47]
https://github.com/yugabyte/yb-tools/blob/3bcd3d526f0311944d932c98c99de60c41da4cf2/tablet-report-parser/tablet-report-parser.pl#L353

The above error gets triggered if we have empty nodes.  There are cases, such as blacklisted tservers where it is expected to be empty.

**Comment by na6vj** [comment]
Do you have a tablet report that shows this parsing error ?
Please attach

**Comment by na6vj** [comment]
Fixed with commit 895b85b0998815a2bad69d32d17940a00b58ae51 on the tablet-server-dev" branch.
It will now correctly parse the tablet report `tablet-report-cud2-006925.out`  attached to ZD-5296, and report:
`Processing TABLET from [ Tablet Report: [host:"10.88.16.83"  port:9100] (f8a1bcbc34104999900fb66523439608) ] (Line#5162)
... 0 TABLET items processed.
`
